export { About } from "./components/About";
export { Contacts } from "./components/Contacts";
export { CustomBusiness } from "./components/CustomBusiness";
export { Footer } from "./components/Footer";
export { Header } from "./components/Header";
export { Hero } from "./components/Hero";
export { Partners } from "./components/Partners";
export { Projects } from "./components/Projects";
export { ForOwners } from './components/ForOwners';